import type { Product, StockMovement } from './types';
import { subDays, addDays, format } from 'date-fns';

const today = new Date();

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Botox Allergan 100u',
    category: 'Injetáveis',
    photoURL: 'https://placehold.co/128x128.png',
    'data-ai-hint': 'medical vial',
    currentStock: 5,
    minimumStock: 10,
    unit: 'Un',
    expiryDate: format(addDays(today, 6), 'yyyy-MM-dd'), // Vence em 6 dias
    batchNumber: 'ABC123',
    supplier: 'Fornecedor ABC',
    costPrice: 450.00,
  },
  {
    id: '2',
    name: 'Ácido Hialurônico 1ml',
    category: 'Injetáveis',
    photoURL: 'https://placehold.co/128x128.png',
    'data-ai-hint': 'medical syringe',
    currentStock: 15,
    minimumStock: 5,
    unit: 'Ampola',
    expiryDate: format(addDays(today, 25), 'yyyy-MM-dd'), // Vence em 25 dias
    batchNumber: 'DEF456',
    supplier: 'Fornecedor XYZ',
    costPrice: 280.00,
  },
  {
    id: '3',
    name: 'Luvas Descartáveis (Caixa)',
    category: 'Materiais Descartáveis',
    photoURL: 'https://placehold.co/128x128.png',
    'data-ai-hint': 'gloves box',
    currentStock: 3,
    minimumStock: 5,
    unit: 'Caixa',
    expiryDate: format(addDays(today, 365), 'yyyy-MM-dd'),
    batchNumber: 'GHI789',
    supplier: 'Distribuidora Saúde',
    costPrice: 45.00,
  },
  {
    id: '4',
    name: 'Creme Hidratante Profissional',
    category: 'Cosméticos Profissionais',
    photoURL: 'https://placehold.co/128x128.png',
    'data-ai-hint': 'cosmetic cream',
    currentStock: 20,
    minimumStock: 10,
    unit: 'Frasco',
    expiryDate: format(addDays(today, 180), 'yyyy-MM-dd'),
    batchNumber: 'JKL012',
    supplier: 'Cosméticos Beauty',
    costPrice: 120.00,
  },
  {
    id: '5',
    name: 'Agulhas 30G (Caixa)',
    category: 'Materiais Descartáveis',
    photoURL: 'https://placehold.co/128x128.png',
    'data-ai-hint': 'needles box',
    currentStock: 8,
    minimumStock: 10,
    unit: 'Caixa',
    expiryDate: format(subDays(today, 10), 'yyyy-MM-dd'), // Vencido
    batchNumber: 'MNO345',
    supplier: 'Distribuidora Saúde',
    costPrice: 75.00,
  },
];

export const mockMovements: StockMovement[] = [
  {
    id: 'mov1',
    productId: '1',
    productName: 'Botox Allergan 100u',
    type: 'saida',
    quantity: 1,
    reason: 'Uso',
    date: format(subDays(today, 1), 'yyyy-MM-dd'),
    previousStock: 6,
    newStock: 5,
  },
  {
    id: 'mov2',
    productId: '2',
    productName: 'Ácido Hialurônico 1ml',
    type: 'entrada',
    quantity: 10,
    reason: 'Compra',
    date: format(subDays(today, 5), 'yyyy-MM-dd'),
    previousStock: 5,
    newStock: 15,
  },
  {
    id: 'mov3',
    productId: '3',
    productName: 'Luvas Descartáveis (Caixa)',
    type: 'saida',
    quantity: 1,
    reason: 'Uso',
    date: format(subDays(today, 2), 'yyyy-MM-dd'),
    previousStock: 4,
    newStock: 3,
  },
  {
    id: 'mov4',
    productId: '5',
    productName: 'Agulhas 30G (Caixa)',
    type: 'saida',
    quantity: 2,
    reason: 'Perda',
    date: format(subDays(today, 15), 'yyyy-MM-dd'),
    previousStock: 10,
    newStock: 8,
  },
];
